### ISSUE TITLE
Twitch changed the way their button UI works, now the button is just a white square

### ISSUE THREAD

**Issue by brian6932** [c-rainbow/twitch-audio-web#8]
FrankerFacez fixed it on their end: 
![image](https://user-images.githubusercontent.com/18603393/102579841-54317c00-40cb-11eb-98da-8aa556a0dbf0.png)

**Comment by c-rainbow** [comment]
Thank you for the report. The fix was pushed in the repository and is pending review in Chrome Web Store.

I'll close this issue once the new version passes the review
